name: 'Russian Holiday Calendar'
description: 'Update iCalendar based on http://xmlcalendar.ru.'

author: Vladislav Sidelnikov <kerihoros@gmail.com>

inputs:
  working_directory:
    description: Default directory
    required: false
    default: ''
  token:
    description: GitHub token
    required: true

outputs:
  commit_message:
    description: 'Message for commit changes'

runs:
  using: 'node16'
  main: 'dist/index.js'
